### ISSUE TITLE
Packages with only usage of Symfony services/config in .yml are detected as unused

### ISSUE THREAD

**Issue by Destroy666x** [Insolita/unused-scanner#9]
#### Code example of package classes usage that not detected: -

E.g. if the only reference to `willdurand/geocoder-bundle` is `- '@bazinga_geocoder.geocoder'` as a DI argument for a service and in my service I construct it with a class from a different package as I have to (`use Geocoder\ProviderAggregator;`), it's not detected.

**Comment by Insolita** [comment]
Please, show you scanner_config.php 
Have you defined 'extensions' => `['*.php', '*.yml']`, in config, for parsing yml configuration?  
Can you show me a piece of .yml where your dependencies declared (with class namespaces)?

**Comment by Destroy666x** [comment]
```
<?php
/**
 *  Set $projectPath = getcwd(); if your put it under project root
 **/
$projectPath = __DIR__;

/**
 * Array of full directories path for scan;
 * Scan will be recursive
 * Put directories with most intensive imports in top of list for more quick result
 * @see http://api.symfony.com/4.0/Symfony/Component/Finder/Finder.html#method_in
 **/
$scanDirectories = [
    $projectPath . '/src/A2I/GeoBundle',
];

$scanFiles = [];

/**
 * Names relative to ones of scanDirectories
 *
 * @see http://api.symfony.com/4.0/Symfony/Component/Finder/Finder.html#method_exclude
 **/
$excludeDirectories = [];
return [
    /**
     * Required params
     **/
    'composerJsonPath' => $projectPath . '/composer.json',
    'vendorPath' => $projectPath . '/vendor/',
    'scanDirectories' => $scanDirectories,

    /**
     * Optional params
     **/
    'excludeDirectories' => $excludeDirectories,
    'scanFiles' => $scanFiles,
    'extensions' => ['*.php', '*.yml'],
    'requireDev' => true,   //Check composer require-dev section, default false
    /**
     * Optional, custom logic for check is file contains definitions of package
     *
     * @example
     * 'customMatch'=> function($definition, $packageName, \Symfony\Component\Finder\SplFileInfo $file):bool{
     *         $isPresent = false;
     *         if($packageName === 'phpunit/phpunit'){
     *              $isPresent = true;
     *         }
     *          if($file->getExtension()==='twig'){
     *            $isPresent = customCheck();
     *          }
     *         return $isPresent;
     * }
     **/
    'customMatch'=> null,

    /**
     * Report mode options
     * Report mode enabled, when reportPath value is valid directory path
     * !!!Note!!! The scanning time and memory usage will be increased when report mode enabled,
     * it sensitive especially for big projects and  when requireDev option enabled
     **/

    'reportPath' => null, //path in directory, where usage report will be stores;

    /**
     * Optional custom formatter (by default report stored as json)
     * $report array format
     * [
     *     'packageName'=> [
     *           'definition'=>['fileNames',...]
     *           ....
     *      ]
     *      ...
     * ]
     *
     * @example
     *  'reportFormatter'=>function(array $report):string{
     *     return print_r($report, true);
     * }
     **/
    'reportFormatter'=>null,
    'reportExtension'=>null, //by default - json, set own, if use custom formatter
];
```

src/A2I/GeoBundle/Resources/config/services/fixtures.yml
```
    a2i_geo.command.convert_city_layer_to_fixtures:
        class: A2I\GeoBundle\Command\ConvertToFixtures\ConvertCityLayerToFixturesCommand
        arguments:
            - '@a2i_geo.helper.file.ogr_feature_data_collector'
            - '@a2i_geo.factory.dto.skipped_item'
            - '@bazinga_geocoder.geocoder'
        tags:
            - name: console.command
```
